<?php
/**
 * @file
 * fail2ban, a one-function module to trigger Fail2ban.
 * Trigger on HTTP/403 and 404 and login failure.
 */

/**
 * Hook watchdog to get 403/404/failed login requests
 * @see drupal_deliver_html_page
 * includes/common.php:2601
 */
function fail2ban_404_watchdog( $log_entry ) {

    $prefix = 'Malicious traffic detected: ';
    $slug = '';

    switch ( $log_entry['type'] ) {
        case 'page not found':
            $slug = '404_not_found';
            break;
        case 'access denied':
            $slug = '403_forbidden';
            break;
        case 'user':
            if ( substr( $log_entry['message'], 0, 25 ) === 'Login attempt failed for ' ) {
                $slug = 'login_failed';
            }
            break;
    }

    if ( empty( $slug ) ) {
        return;
    }

    // When error messages are sent to a file (aka. PHP error log)
    // IP address and referer are not logged
    $log_destination = ini_get( 'error_log' );

    // SAPI should add client data
    $included_files = get_included_files();
    $error_msg = sprintf( '%s%s (%s) <%s',
        $prefix,
        $slug,
        addslashes( $log_entry['request_uri'] ),
        reset( $included_files )
    );

    // Add client data to log message
    if ( ! empty( $log_destination ) ) {
        if ( array_key_exists( 'HTTP_REFERER', $_SERVER ) ) {
            $referer = sprintf( ', referer: %s', addslashes( $_SERVER['HTTP_REFERER'] ) );
        } else {
            $referer = '';
        }

        $error_msg = sprintf( '[error] [client %s:%s] %s%s',
            $_SERVER['REMOTE_ADDR'],
            $_SERVER['REMOTE_PORT'],
            $error_msg,
            $referer
        );
    }

    error_log( $error_msg );
}
